global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'matchmovie-backend'
    static_configs:
      - targets: ['${BACKEND_HOST}:${BACKEND_PORT}']
    metrics_path: '/metrics'
    scheme: ${BACKEND_SCHEME} 